{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  destination:
    name: {{ .cluster }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ default "main" .targetRevision }}
    path: {{ .path }}
  {{- if .autosync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  {{- end }}
---
{{- end }}
