{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  destination:
    name: {{ .cluster }}
    namespace: {{ .namespace }}
  source:
    repoURL: https://github.com/celeguim/DevOps.git
    targetRevision: main
    path: {{ .path }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
{{- end }}
