apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-root-minikube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/celeguim/DevOps.git
    targetRevision: main
    path: ArgoCD/charts
    helm:
      valueFiles:
        - applications/minikube/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: celeghin
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
